"use client";

/**
 * Demo scenario picker (@frontend.eng, live-demo support).
 *
 * OFF unless switched on: `NEXT_PUBLIC_DEMO_MODE=1` at build time, or `?demo=1` on the URL. A
 * customer must never see this — it exposes other people's order ids, and a support surface that
 * offers a menu of strangers' orders is a different product with a different security finding.
 *
 * It fills the form; it does not send. The presenter still presses Run, so the audience sees a
 * real turn start from a real click rather than a canned playback, and a question can still be
 * edited before it goes. That distinction is the entire value of demoing the actual app.
 *
 * Scenarios come from `data/demo-scenarios.json`, generated by `npm run demo:build` against the
 * live database — the ids are real rows and the day counts are computed from the pinned
 * AS_OF_DATE, so nothing here can quietly go stale between a rehearsal and the room.
 */

import { useState } from "react";
import styles from "./DemoBar.module.css";

export type DemoScenario = {
  id: string;
  title: string;
  message: string;
  identity: { orderId?: number; userId?: number };
  expect: { status: string; agent: string; reasonCode?: string; note: string };
  exercises: string[];
};

type Props = {
  scenarios: readonly DemoScenario[];
  onPick: (s: DemoScenario) => void;
  disabled: boolean;
};

/** Terminal status drives the chip's tone, so the presenter can see at a glance which of the
 *  three outcomes a scenario is meant to produce before they run it. */
const TONE: Record<string, string | undefined> = {
  resolved: styles.resolved,
  escalated: styles.escalated,
  needs_input: styles.needsInput,
};

export default function DemoBar({ scenarios, onPick, disabled }: Props) {
  const [open, setOpen] = useState(true);
  const [active, setActive] = useState<string | null>(null);

  const current = scenarios.find((s) => s.id === active) ?? null;

  return (
    <section className={styles.bar} aria-label="Demo scenarios">
      <div className={styles.head}>
        <button
          type="button"
          className={styles.toggle}
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
        >
          <span className={styles.caret} aria-hidden="true">
            {open ? "▾" : "▸"}
          </span>
          Demo scenarios
          <span className={styles.count}>{scenarios.length}</span>
        </button>
        <span className={styles.hint}>Fills the form — you still press Run</span>
      </div>

      {open && (
        <>
          <div className={styles.chips}>
            {scenarios.map((s) => (
              <button
                key={s.id}
                type="button"
                disabled={disabled}
                className={`${styles.chip} ${TONE[s.expect.status] ?? ""} ${
                  active === s.id ? styles.active : ""
                }`}
                onClick={() => {
                  setActive(s.id);
                  onPick(s);
                }}
                title={s.expect.note}
              >
                {s.title}
              </button>
            ))}
          </div>

          {/* What the presenter needs in the two seconds before they press Run: which agent
              should take it, what the terminal status should be, and why this case exists. */}
          {current !== null && (
            <p className={styles.detail}>
              <code>{current.expect.agent}</code>
              <span className={styles.sep}>·</span>
              <code>{current.expect.status}</code>
              {current.expect.reasonCode !== undefined && (
                <>
                  <span className={styles.sep}>·</span>
                  <code>{current.expect.reasonCode}</code>
                </>
              )}
              <span className={styles.note}>{current.expect.note}</span>
            </p>
          )}
        </>
      )}
    </section>
  );
}
