/**
 * Human-readable artifacts for an escalation: the ticket packet, and a simulated outbound email.
 *
 * WHY THESE ARE NOT TOOLS.
 *
 * `create_ticket_stub` states the rule three times over: the runtime records what it OBSERVED,
 * and the model is never asked to reproduce an observation it might forget, misremember, or
 * invent. These artifacts are observations of an escalation that already happened, so they are
 * written by the runtime on the success path — guaranteed, in a fixed format, with no output
 * tokens spent and no chance of being skipped.
 *
 * The second reason matters more. Adding a `send_email` tool would hand a model an OUTBOUND
 * COMMUNICATION capability, in a system whose safety claim is that every tool is asserted by
 * name and none of them can act on the customer's behalf. "It is only simulated" is not a
 * defence: `toolRegistry.test.ts` asserts the registered set EQUALS a literal precisely so that
 * a new capability cannot arrive quietly, and the honest way to add one is to argue for it, not
 * to slip it in behind a demo.
 *
 * NOTHING HERE SENDS ANYTHING. `data/outbox.md` is a file. There is no SMTP client, no API
 * call, no network egress of any kind in this module — and the file says so at the top, in case
 * it is ever read out of context.
 *
 * PRIVACY. These files carry the same customer content the trace logs do (SEC-03), so they run
 * through the same `scrubPii` and live under `data/`, which is gitignored. They inherit the
 * trace retention window: `npm run prune:traces` sweeps them on the same schedule.
 */

import { appendFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { scrubPii } from "./trace";

const TICKET_DIR = path.join(process.cwd(), "data", "tickets");
const OUTBOX = path.join(process.cwd(), "data", "outbox.md");

/** Shape written by `createTicketStub`, narrowed to what an artifact needs. */
export type HandoffStub = {
  ticket_stub_id: string;
  conversation_id?: string;
  intent: string;
  reason_code: string;
  suggested_category: string;
  urgency: string;
  transcript_summary: string;
  entities: Record<string, unknown>;
  tools_tried?: ReadonlyArray<{ tool: string; ok: boolean; summary?: string }>;
  citations?: readonly string[];
  created_at?: string;
};

const clean = (value: string): string => scrubPii(value);

function entityLines(entities: Record<string, unknown>): string {
  const rows = Object.entries(entities).filter(([, v]) => v !== undefined && v !== null);
  if (rows.length === 0) return "_None captured._";
  return rows.map(([k, v]) => `- **${k}**: ${clean(String(v))}`).join("\n");
}

/**
 * The packet a human agent picks up.
 *
 * Ordered for someone who has thirty seconds and a queue: what is being asked, who it is about,
 * and what has already been tried — so the first thing they do is not repeat a lookup the crew
 * already did. `tools_tried` is the runtime's ledger, including FAILED calls, because "we tried
 * and it errored" is the most useful line on the page and the one a model would omit.
 */
function ticketMarkdown(stub: HandoffStub, asOf: string): string {
  const tried = (stub.tools_tried ?? []).map(
    (t) => `| \`${t.tool}\` | ${t.ok ? "ok" : "**failed**"} | ${clean(t.summary ?? "")} |`,
  );
  const cites = (stub.citations ?? []).map((c) => `- \`${c}\``);

  return `# Ticket ${stub.ticket_stub_id}

> Handed off by the NovaMart support crew. **No money has moved and nothing has been promised
> to the customer beyond "a human will pick this up".** The crew has no refund, cancel or
> payment capability — see \`security.md\`.

| | |
| --- | --- |
| **Reason** | \`${stub.reason_code}\` |
| **Category** | ${clean(stub.suggested_category)} |
| **Urgency** | ${stub.urgency} |
| **Intent** | ${clean(stub.intent)} |
| **Conversation** | \`${stub.conversation_id ?? "unknown"}\` |
| **Opened** | ${stub.created_at ?? asOf} |

## What the customer wants

${clean(stub.transcript_summary)}

## Who and what this is about

${entityLines(stub.entities)}

## Already tried by the crew

${
  tried.length > 0
    ? `| Tool | Result | Detail |\n| --- | --- | --- |\n${tried.join("\n")}`
    : "_No tool calls were made on this turn._"
}

${cites.length > 0 ? `## Grounded in\n\n${cites.join("\n")}\n` : ""}
---
_Generated by the runtime on escalation. Not model-authored — every field above is either the
customer's own words or something the runtime watched happen._
`;
}

/**
 * A simulated outbound notification, appended to one ongoing file.
 *
 * Append rather than overwrite so the file reads as a queue building up across a session, which
 * is the point during a demo: one file, opened once, that grows as the crew hands work over.
 */
function emailEntry(stub: HandoffStub, asOf: string): string {
  const order = stub.entities["order_id"];
  const subject = `[${stub.reason_code}] Ticket ${stub.ticket_stub_id}${
    order === undefined ? "" : ` — order ${String(order)}`
  }`;

  return `
## ${stub.created_at ?? asOf} — ${subject}

**To:** support-queue@novamart.example (simulated)
**From:** novamart-support-crew (automated)
**Ticket:** \`${stub.ticket_stub_id}\` · **Urgency:** ${stub.urgency} · **Category:** ${clean(stub.suggested_category)}

${clean(stub.transcript_summary)}

Details: ${
    Object.entries(stub.entities)
      .filter(([, v]) => v !== undefined && v !== null)
      .map(([k, v]) => `${k}=${clean(String(v))}`)
      .join(" · ") || "none captured"
  }
Full packet: \`data/tickets/${stub.ticket_stub_id}.md\`

---
`;
}

const OUTBOX_HEADER = `# Simulated outbound queue

**Nothing in this file was sent.** There is no mail client, no API call and no network egress
anywhere in this system — \`server/runtime/handoffArtifacts.ts\` appends to this file and does
nothing else. It exists so a handoff is visible as something a person would receive, rather than
as a ticket id on a screen.

Contains customer content: gitignored, PII-scrubbed at write, and swept by
\`npm run prune:traces\` on the trace retention window.

`;

/**
 * Best-effort, never awaited on the hot path, never able to fail a turn.
 *
 * Identical discipline to `trace.ts`: an unwritten demo artifact is worth strictly less than the
 * customer's answer, so every failure here is swallowed after a warning.
 */
export function writeHandoffArtifacts(stub: HandoffStub, asOf: string): void {
  void (async () => {
    await ensureOutboxHeader();
    await mkdir(TICKET_DIR, { recursive: true });
    await writeFile(
      path.join(TICKET_DIR, `${stub.ticket_stub_id}.md`),
      ticketMarkdown(stub, asOf),
      "utf8",
    );
    // `flag: "a"` creates the file when absent, so the header is written exactly once.
    await appendFile(OUTBOX, emailEntry(stub, asOf), "utf8");
  })().catch((err: unknown) => {
    console.warn("handoff artifact write failed (non-fatal)", err);
  });
}

/** Writes the outbox header if the file does not exist yet. Called once, lazily. */
export async function ensureOutboxHeader(): Promise<void> {
  try {
    await mkdir(path.dirname(OUTBOX), { recursive: true });
    await writeFile(OUTBOX, OUTBOX_HEADER, { flag: "wx" });
  } catch {
    /* already exists — the normal case */
  }
}

export const OUTBOX_PATH = OUTBOX;
export const TICKET_DIR_PATH = TICKET_DIR;
